### ISSUE TITLE
Aternos Crash

### ISSUE THREAD

**Issue by XxMicrowavexX** [PlanetTeamSpeakk/MoreCommands#47] opened 2021-11-15 02:14 UTC
Hi me and my freinds have a aternos server. I installed the mod and it said it was having a error relating to fluid rendering also something I thought was important is that the it was a warning but the game still crashed. It said that I was using a new version of the fluid renderer and to install the old version v0. So to be sure which version of fabric API I needed I deleted it and started it. It said it required fabric api0.36.1+1.17 so I installed it and started it. Now the log says:

[15:10:27] [main/INFO]: Loading for game Minecraft 1.17.1
--
2 | [15:10:27] [main/INFO]: Loading 37 mods:
3 | - fabric 0.36.1+1.17
4 | - fabric-api-base 0.3.0+a02b446313
5 | - fabric-api-lookup-api-v1 1.2.0+2b5c62d013
6 | - fabric-biome-api-v1 3.1.11+c345aea813
7 | - fabric-command-api-v1 1.1.2+6cefd57713
8 | - fabric-commands-v0 0.2.2+92519afa13
9 | - fabric-containers-v0 0.1.12+a02b446313
10 | - fabric-content-registries-v0 0.2.2+a02b446313
11 | - fabric-crash-report-info-v1 0.1.5+be9da31013
12 | - fabric-dimensions-v1 2.0.11+6cefd57713
13 | - fabric-entity-events-v1 1.1.0+a02b446313
14 | - fabric-events-interaction-v0 0.4.9+a722d8c013
15 | - fabric-events-lifecycle-v0 0.2.1+92519afa13
16 | - fabric-game-rule-api-v1 1.0.7+6cefd57713
17 | - fabric-item-api-v1 1.2.4+a02b446313
18 | - fabric-item-groups-v0 0.2.10+b7ab612113
19 | - fabric-lifecycle-events-v1 1.4.4+a02b446313
20 | - fabric-loot-tables-v1 1.0.4+a02b446313
21 | - fabric-mining-levels-v0 0.1.3+92519afa13
22 | - fabric-networking-api-v1 1.0.12+6cefd57713
23 | - fabric-networking-blockentity-v0 0.2.11+a02b446313
24 | - fabric-networking-v0 0.3.2+92519afa13
25 | - fabric-object-builder-api-v1 1.10.9+b7ab612113
26 | - fabric-object-builders-v0 0.7.3+a02b446313
27 | - fabric-particles-v1 0.2.4+a02b446313
28 | - fabric-registry-sync-v0 0.7.10+e2961fee13
29 | - fabric-rendering-data-attachment-v1 0.1.5+a02b446313
30 | - fabric-resource-loader-v0 0.4.7+b7ab612113
31 | - fabric-screen-handler-api-v1 1.1.8+a02b446313
32 | - fabric-structure-api-v1 1.1.12+6cefd57713
33 | - fabric-tag-extensions-v0 1.1.4+a02b446313
34 | - fabric-tool-attribute-api-v1 1.2.12+b7ab612113
35 | - fabricloader 0.12.5
36 | - java 16
37 | - minecraft 1.17.1
38 | - morecommands 3.8.1
39 | - voicechat 1.17.1-2.1.5
40 | [15:10:28] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/server/fabric.jar Service=Knot/Fabric Env=SERVER
41 | [15:10:28] [main/INFO]: Compatibility level set to JAVA_16

Which makes NO sense. how is there a crash with no error wtf. Im no java dev or mod dev but ik from my programming language that a game can't crash from a warning let alone nothing

**Comment by XxMicrowavexX** [comment] 2021-11-15 02:59
Also ium using the latest version

**Comment by XxMicrowavexX** [comment] 2021-11-15 21:09
HEY i got some more info
10:08:53] [INFO] [FabricLoader/GameProvider]: Loading for game Minecraft 1.17.1
[10:08:55] [main/INFO]: Loading for game Minecraft 1.17.1
[10:08:55] [main/INFO]: Loading 36 mods:
	- fabric 0.36.1+1.17
	- fabric-api-base 0.3.0+a02b446313
	- fabric-api-lookup-api-v1 1.2.0+2b5c62d013
	- fabric-biome-api-v1 3.1.11+c345aea813
	- fabric-command-api-v1 1.1.2+6cefd57713
	- fabric-commands-v0 0.2.2+92519afa13
	- fabric-containers-v0 0.1.12+a02b446313
	- fabric-content-registries-v0 0.2.2+a02b446313
	- fabric-crash-report-info-v1 0.1.5+be9da31013
	- fabric-dimensions-v1 2.0.11+6cefd57713
	- fabric-entity-events-v1 1.1.0+a02b446313
	- fabric-events-interaction-v0 0.4.9+a722d8c013
	- fabric-events-lifecycle-v0 0.2.1+92519afa13
	- fabric-game-rule-api-v1 1.0.7+6cefd57713
	- fabric-item-api-v1 1.2.4+a02b446313
	- fabric-item-groups-v0 0.2.10+b7ab612113
	- fabric-lifecycle-events-v1 1.4.4+a02b446313
	- fabric-loot-tables-v1 1.0.4+a02b446313
	- fabric-mining-levels-v0 0.1.3+92519afa13
	- fabric-networking-api-v1 1.0.12+6cefd57713
	- fabric-networking-blockentity-v0 0.2.11+a02b446313
	- fabric-networking-v0 0.3.2+92519afa13
	- fabric-object-builder-api-v1 1.10.9+b7ab612113
	- fabric-object-builders-v0 0.7.3+a02b446313
	- fabric-particles-v1 0.2.4+a02b446313
	- fabric-registry-sync-v0 0.7.10+e2961fee13
	- fabric-rendering-data-attachment-v1 0.1.5+a02b446313
	- fabric-resource-loader-v0 0.4.7+b7ab612113
	- fabric-screen-handler-api-v1 1.1.8+a02b446313
	- fabric-structure-api-v1 1.1.12+6cefd57713
	- fabric-tag-extensions-v0 1.1.4+a02b446313
	- fabric-tool-attribute-api-v1 1.2.12+b7ab612113
	- fabricloader 0.12.5
	- java 16
	- minecraft 1.17.1
	- morecommands 3.8.1
[10:08:56] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.4 Source=file:/server/fabric.jar Service=Knot/Fabric Env=SERVER
[10:08:56] [main/INFO]: Compatibility level set to JAVA_16
Exception in thread "main" java.lang.RuntimeException: Failed to setup Fabric server environment!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:62)
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:100)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:60)
Caused by: java.lang.RuntimeException: An exception occurred when launching the server!
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:74)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:98)
	... 1 more
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:567)
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:72)
	... 2 more
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.server.Main failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:224)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:133)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:519)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:566)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23)
	... 7 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:222)
	... 13 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Callback method main([Ljava/lang/String;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V in morecommands.server_mixins.json:MixinMain from mod morecommands failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap MoreCommands-refmap.json
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:468)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1381)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1052)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:400)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 16 more

**Comment by XxMicrowavexX** [comment] 2021-11-15 21:18
ive done all the detective work i can its up to u know

**Comment by XxMicrowavexX** [comment] 2021-11-20 23:04
wtf its been 6 days

**Comment by PlanetTeamSpeakk** [comment] 2021-11-21 10:33
I can't help you if there's no error anywhere. It's impossible to find the cause that way.

**Comment by PlanetTeamSpeakk** [comment] 2021-11-21 10:34
I've been rather busy, have patience.

**Comment by PlanetTeamSpeakk** [comment] 2021-11-23 19:58
Fairly certain this is due to you using Fabric 12.x rather than 11.x, if so, fixed in upcoming release.

**Closed as completed by PlanetTeamSpeakk** 2021-11-23 19:58 UTC
Labels: bug
