### ISSUE TITLE
/fakeplayer doesn't support skins with an extra layer

### ISSUE THREAD

**Issue by karstenzip** [PlanetTeamSpeakk/MoreCommands#30] opened 2021-07-17 15:11 UTC
When you use /fakeplayer create Dinnerbone it makes the fake player Dinnerbone, but the 2nd layer is missing. Please add support for this

**Comment by PlanetTeamSpeakk** [comment] 2021-07-17 15:22
Duplicate of #18

**Closed as completed by PlanetTeamSpeakk** 2021-07-17 15:22 UTC
