### ISSUE TITLE
Frabric 1.19 no start server

### ISSUE THREAD

**Issue by Anhelm** [PlanetTeamSpeakk/MoreCommands#76] opened 2022-10-01 06:54 UTC
```
[09:52:47] [main/INFO]: Loading Minecraft 1.19 with Fabric Loader 0.14.9
[09:52:47] [ForkJoinPool-1-worker-11/WARN]: The mod "sculksieg" contains invalid entries in its mod json:
- Unsupported root entry "pack_format" at line 15 column 18
[09:52:47] [ForkJoinPool-1-worker-12/WARN]: The mod "dungeons_arise" contains invalid entries in its mod json:
- Unsupported root entry "credits" at line 12 column 12
[09:52:47] [ForkJoinPool-1-worker-6/WARN]: The mod "rpg_origins" contains invalid entries in its mod json:
- Unsupported root entry "pack_format" at line 15 column 18
[09:52:47] [ForkJoinPool-1-worker-2/WARN]: Mod letmedespawn uses the version fabric-1.0.2 which isn't compatible with Loader's extended semantic version format (Could not parse version number component 'fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[09:52:47] [ForkJoinPool-1-worker-4/WARN]: Mod globaldataandresourcepacks uses the version 1.14.2_fabric which isn't compatible with Loader's extended semantic version format (Could not parse version number component '2_fabric'!), SemVer is recommended for reliably evaluating dependencies and prioritizing newer version
[09:52:47] [ForkJoinPool-1-worker-7/WARN]: The mod "extra_classes_origins" contains invalid entries in its mod json:
- Unsupported root entry "pack_format" at line 15 column 18
[09:52:48] [main/INFO]: Loading 217 mods:
	- additionalentityattributes 1.0.0+1.19 via apoli
	- adorn 3.6.1+1.19
	- advdebug 2.3.0
	- adventure-platform-fabric 5.4.0-SNAPSHOT via minimotd-fabric
	- alternate-current 1.4.0
	- amethystequipment 1.0.5
	- antixray 1.2.4
	- anvilrestoration-fabric 1.3
	- apoli 2.5.1 via origins
	- appleskin 2.4.1+mc1.19
	- arcanus 1.30
	- architectury 5.12.45
	- autoconfig1u 3.4.0 via rpgstats
	- backpackmod 4.0.5
	- badpackets 0.1.2
	- balm-fabric 4.5.2+0
	- blockus 2.5.1+1.19
	- blue_endless_jankson 1.2.1 via jankson
	- boneequipment 1.0.4
	- bookshelf 14.2.10
	- bosses_of_mass_destruction 1.4.2-1.19
	- byg 2.0.0.7
	- calio 1.7.0 via apoli
	- cardinal-components 5.0.1
	- cardinal-components-base 5.0.1 via cardinal-components
	- cardinal-components-block 5.0.1 via cardinal-components
	- cardinal-components-chunk 5.0.1 via cardinal-components
	- cardinal-components-entity 5.0.1 via cardinal-components
	- cardinal-components-item 5.0.1 via cardinal-components
	- cardinal-components-level 5.0.1 via cardinal-components
	- cardinal-components-scoreboard 5.0.1 via cardinal-components
	- cardinal-components-world 5.0.1 via cardinal-components
	- chunky 1.2.217
	- clickadv 2.9
	- cloth-basic-math 0.6.1 via cloth-config
	- cloth-config 8.1.77
	- collective-fabric 4.27
	- com_electronwill_night-config_core 3.6.5 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.5 via forgeconfigapiport
	- com_eliotlash_mclib_mclib 18 via geckolib3
	- com_eliotlash_molang_molang 18 via geckolib3
	- com_moandjiezana_toml_toml4j 0.7.2 via antixray
	- com_velocitypowered_velocity-native 3.1.2-SNAPSHOT via krypton
	- connectivity 1.19-3.2
	- darkbindings 1.0.7
	- darkquesting 1.0.3
	- dataattributes 1.2.6
	- diamond_nuggets 1.3
	- diamondchestshop 1.2.4-1.19
	- diamondeconomy 1.5.4
	- diamondsauctionhouse 1.1.3
	- dragonloot 1.1.1
	- dummmmmmy 1.19-1.5.3
	- dungeons_arise 2.1.51
	- ellemes_container_lib 2.0.1
	- emeraldequipment 1.0.4
	- emi 0.4.0+1.19
	- enchant_giver 1.3.0 via mcdw
	- exlinecopperequipment 2.1.1
	- expandedstorage 8.0.1
	- extra_classes_origins 1.0.0
	- extraorigins 1.19-2
	- fabric 0.58.0+1.19
	- fabric-api-base 0.4.9+e62f51a3a9 via servercore
	- fabric-api-lookup-api-v1 1.6.7+9ff28f40a9 via fabric
	- fabric-biome-api-v1 9.0.14+b2a4a624a9 via fabric
	- fabric-command-api-v1 1.2.6+f71b366fa9 via fabric
	- fabric-command-api-v2 2.1.2+0d55f585a9 via servercore
	- fabric-commands-v0 0.2.23+df3654b3a9 via fabric
	- fabric-containers-v0 0.1.28+df3654b3a9 via fabric
	- fabric-content-registries-v0 3.2.1+07df213ea9 via fabric
	- fabric-convention-tags-v1 1.0.8+37622d24a9 via fabric
	- fabric-crash-report-info-v1 0.2.3+bd0a0d4aa9 via fabric
	- fabric-data-generation-api-v1 5.1.2+a680b9b4a9 via fabric
	- fabric-dimensions-v1 2.1.28+a6d2f785a9 via fabric
	- fabric-entity-events-v1 1.4.16+9ff28f40a9 via fabric
	- fabric-events-interaction-v0 0.4.26+9ff28f40a9 via fabric
	- fabric-events-lifecycle-v0 0.2.26+df3654b3a9 via fabric
	- fabric-game-rule-api-v1 1.0.19+18990361a9 via fabric
	- fabric-item-api-v1 1.5.5+35a03c43a9 via fabric
	- fabric-item-groups-v0 0.3.26+9ff28f40a9 via fabric
	- fabric-language-kotlin 1.8.3+kotlin.1.7.10
	- fabric-lifecycle-events-v1 2.1.0+33fbc738a9 via servercore
	- fabric-loot-api-v2 1.1.1+03a4e568a9 via fabric
	- fabric-loot-tables-v1 1.1.4+9e7660c6a9 via fabric
	- fabric-message-api-v1 1.0.1+513f4a59a9 via fabric
	- fabric-mining-level-api-v1 2.1.11+33fbc738a9 via fabric
	- fabric-networking-api-v1 1.1.0+442de8b8a9 via fabric
	- fabric-networking-v0 0.3.15+df3654b3a9 via fabric
	- fabric-object-builder-api-v1 4.0.8+9ff28f40a9 via fabric
	- fabric-particles-v1 1.0.8+dc39553aa9 via fabric
	- fabric-permissions-api-v0 0.2-SNAPSHOT via luckperms
	- fabric-registry-sync-v0 0.9.18+23c4cfefa9 via fabric
	- fabric-rendering-data-attachment-v1 0.3.12+9ff28f40a9 via fabric
	- fabric-rendering-fluids-v1 3.0.5+9ff28f40a9 via fabric
	- fabric-resource-conditions-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-resource-loader-v0 0.5.6+5f1a85e0a9 via fabric
	- fabric-screen-handler-api-v1 1.2.7+9ff28f40a9 via fabric
	- fabric-transfer-api-v1 2.0.9+e62f51a3a9 via fabric
	- fabric-transitive-access-wideners-v1 1.1.1+9e7660c6a9 via fabric
	- fabricloader 0.14.9+local
	- ferritecore 4.2.1
	- fiber 0.23.0-2 via collective-fabric
	- firstjoinmessage-fabric 1.5
	- forgeconfigapiport 4.2.6
	- furnacerecycle-fabric 1.3
	- geckolib3 3.1.6
	- globaldataandresourcepacks 1.14.2_fabric
	- grindstonesharpertools-fabric 1.8
	- healingcampfire-fabric 3.5
	- icarus 1.13
	- iceberg 1.0.46
	- inventoryconfig 1.2.2
	- inventorysorter 1.8.10-1.19
	- jankson 4.1.1+j1.2.1 via libgui
	- java 17
	- just_end_anchor 1.0.2
	- kanos_config 0.3.1+1.14.4-1.19 via pehkui
	- keyblademod 1.0.2
	- kits 1.4.2-mc1.19
	- konkrete 1.5.0
	- krypton 0.2.0
	- kyrptconfig 1.4.14-1.19 via inventorysorter
	- letmedespawn fabric-1.0.2
	- libgui 6.0.0+1.19 via rpgstats
	- libninepatch 1.1.0 via libgui
	- limitedspawners 1.0.5
	- lithium 0.8.1
	- loadingscreentips 1.0.2
	- luckperms 5.4.36
	- maelstrom_library 1.3-1.19-pre1 via bosses_of_mass_destruction
	- magiccombatwands 1.0.2
	- mcda 2.2.0
	- mcdar 1.5.2-1.19
	- mcdw 5.0.3-1.19
	- mcsa 2.4.0-1.19
	- me_hypherionmc_sdlink_sdlink-lib 2.0.2 via sdlink
	- me_lucko_spark-api 0.1-SNAPSHOT via servercore
	- minecraft 1.19
	- mineralchance-fabric 1.8
	- minimotd-fabric 2.0.9
	- morecommands 4.0
	- multipart_entities 1.2-1.19-pre1 via bosses_of_mass_destruction
	- mythicmounts 1.19-7.0
	- net_kyori_adventure-api 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-key 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-platform-api 4.1.1 via adventure-platform-fabric
	- net_kyori_adventure-text-logger-slf4j 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-minimessage 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-gson 4.11.0 via adventure-platform-fabric
	- net_kyori_adventure-text-serializer-plain 4.11.0 via adventure-platform-fabric
	- net_kyori_examination-api 1.3.0 via adventure-platform-fabric
	- net_kyori_examination-string 1.3.0 via adventure-platform-fabric
	- nohostilesaroundcampfire-fabric 4.0
	- obsidianequipment 1.0.4
	- omega-config 1.2.3-1.18.1 via starteritems
	- openpartiesandclaims 0.8.0
	- org_jetbrains_kotlin_kotlin-reflect 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.7.10 via fabric-language-kotlin
	- org_jetbrains_kotlinx_atomicfu-jvm 0.18.3 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.4 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-datetime-jvm 0.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.4.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.4.0 via fabric-language-kotlin
	- org_xerial_sqlite-jdbc 3.36.0.3 via diamondeconomy
	- origins 1.6.2
	- origins-classes 1.4.0
	- originsumbrellas 1.5.3
	- owo 0.7.3+1.19
	- packet_size_doubler 1.2.0
	- packet_tweaker 0.3.0+1.18.2 via server_translations_api
	- patchouli 1.19-74-FABRIC
	- pehkui 3.4.2+1.14.4-1.19.2
	- placeholder-api 2.0.0-beta.7+1.19 via styledchat
	- playerabilitylib 1.6.0 via apoli
	- polymorph 0.45.0+1.19.2
	- rainbegoneritual-fabric 1.9
	- randomtp 7.0.0+1.19
	- reach-entity-attributes 2.3.0 via mcdw
	- recast-fabric 1.7
	- rpg_origins 1.2.1
	- rpgstats 4.3.15+1.19
	- sculksieg 1.0.0
	- sdlink 1.4.0
	- server_translations_api 1.4.14+1.19-rc2 via rpgstats
	- servercore 1.3.1-1.19
	- sgui 1.1.0+1.19 via diamondsauctionhouse
	- smoothchunk 1.19.1-2.0
	- smwyg 1.0.2
	- soulsweapons 0.9.3
	- spark 1.9.26
	- stacc 1.3.4 via stacker
	- stacker 3.0.2-1.19.x
	- starlight 1.1.1+fabric.ae22326
	- starteritems 2.0.2-1.19
	- styledchat 1.3.3+1.19
	- terrablender 2.0.0.117
	- terraform-wood-api-v1 4.1.0 via blockus
	- things 0.2.20+1.19
	- toofast 1.0.0
	- toolleveling 1.19-1.3.3
	- trinkets 3.4.0
	- vanityslots 1.2.0
	- villagernames-fabric 3.6
	- wardentools 1.2
	- waystones 11.1.0
	- welcomemessage-fabric 1.2
	- wildfire_gender 1.19-3.0.0
	- worldborder-fabric 2.7
	- worldedit 7.2.11-beta-02+315c5d0
	- wthit 5.12.0
	- xaerominimapfair 22.12.0
	- xaeroworldmap 1.26.1
[09:52:48] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/home/darkrpg/libraries/net/fabricmc/sponge-mixin/0.11.4+mixin.0.8.5/sponge-mixin-0.11.4+mixin.0.8.5.jar Service=Knot/Fabric Env=SERVER
[09:52:48] [main/INFO]: Compatibility level set to JAVA_17
[09:52:48] [main/INFO]: Loaded configuration file for Lithium: 94 options available, 4 override(s) found
[09:52:48] [main/WARN]: Reference map 'warden-tools-refmap.json' for wardentools.mixins.json could not be read. If this is a development environment you can ignore this message
[09:52:49] [main/WARN]: Error loading class: net/minecraft/class_634 (java.lang.ClassNotFoundException: net/minecraft/class_634)
[09:52:49] [main/WARN]: @Mixin target net.minecraft.class_634 was not found just_end_anchor.mixins.json:ClientPlayerNetworkHandlerMixin from mod just_end_anchor
[09:52:49] [main/WARN]: Force-disabling mixin 'alloc.blockstate.StateMixin' as rule 'mixin.alloc.blockstate' (added by mods [ferritecore]) disables it and children
[09:52:49] [main/WARN]: Force-disabling mixin 'alloc.chunk_ticking.ServerChunkManagerMixin' as rule 'mixin.alloc.chunk_ticking' (added by mods [servercore]) disables it and children
[09:52:49] [main/WARN]: Force-disabling mixin 'entity.collisions.suffocation.EntityMixin' as rule 'mixin.entity.collisions.suffocation' (added by user configuration) disables it and children
[09:52:49] [main/WARN]: Force-disabling mixin 'world.player_chunk_tick.ThreadedAnvilChunkStorageMixin' as rule 'mixin.world.player_chunk_tick' (added by mods [krypton]) disables it and children
[09:52:49] [main/ERROR]: Mixin prepare for mod morecommands failed preparing MixinEntityCallbacks in fabric-morecommands_common.mixins.json: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException Cannot load class fabric.com.ptsmods.morecommands.mixin.common.MixinEntityCallbacks in environment type SERVER
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: Cannot load class fabric.com.ptsmods.morecommands.mixin.common.MixinEntityCallbacks in environment type SERVER
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:865) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepareMixins(MixinConfig.java:852) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinConfig.prepare(MixinConfig.java:777) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.prepareConfigs(MixinProcessor.java:540) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.select(MixinProcessor.java:462) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.checkSelect(MixinProcessor.java:438) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:290) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:416) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:325) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:220) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:159) [fabric-loader-0.14.9.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) [?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:454) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.14.9.jar:?]
	at pro.gravit.launcher.server.launch.ClasspathLaunch.run(ClasspathLaunch.java:21) [ServerWrapper.jar:?]
	at pro.gravit.launcher.server.ServerWrapper.run(ServerWrapper.java:185) [ServerWrapper.jar:?]
	at pro.gravit.launcher.server.ServerWrapper.main(ServerWrapper.java:60) [ServerWrapper.jar:?]
Caused by: java.lang.RuntimeException: Cannot load class fabric.com.ptsmods.morecommands.mixin.common.MixinEntityCallbacks in environment type SERVER
	at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:456) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassBytes(KnotClassDelegate.java:427) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.getClassByteArray(Knot.java:320) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassBytes(MixinServiceKnot.java:60) ~[fabric-loader-0.14.9.jar:?]
	at net.fabricmc.loader.impl.launch.knot.MixinServiceKnot.getClassNode(MixinServiceKnot.java:76) ~[fabric-loader-0.14.9.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.loadMixinClass(MixinInfo.java:1312) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinInfo.<init>(MixinInfo.java:858) ~[sponge-mixin-0.11.4+mixin.0.8.5.jar:0.11.4+mixin.0.8.5]
	... 20 more

```

**Comment by PlanetTeamSpeakk** [comment] 2022-10-01 07:35
Duplicate of #72

**Closed as completed** 2022-10-01 07:35 UTC
